let LineItem = {
	'DeliveryGroupId': 1,
	'ProductId': null,
	'BaseProductId': null,
	'Description': null,
	'InStorePrice': null,
	'InStoreTotalPrice': null,
	'InStoreQuantity': null,
	'ChoiceQuantity': null,
	'QuantityOriginal': null,
	'ChoiceWeight': null,
	'WeightOriginal': null,
	'MaxWeight': null,
	'AverageWeight': null,
	'Weight': null,
	'Volume': null,
	'Type': null,
	'ChargeProductType': null,
	'IsSelectedByQuantity': null,
	'MeasureType': null,
	'UnitOfSale': null,
	'SubstitutionOption': null,
	'LineNumber': null,
	'PickerNote': null,
	'IsNewlyAdded': false,
	'AddedDateTime': null,
	'LastUpdated': null,
	'ExtnIsReturnable': null,
	'ExtnSeller': null
};
export default LineItem;
